In [2]:
#import numpy
import numpy as np

## Creating Numpy Arrays from Python Lists

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
# List in Python can contain different type
[3.14, 4, 2.1, 7]

[3.14, 4, 2.1, 7]

In [5]:
# numpy convert high level type
np.array([3, 14, 4.2, 4])

array([ 3. , 14. ,  4.2,  4. ])

In [7]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [8]:
a1 = np.array([1, 2, 3, 4])

In [9]:
type(a1)

numpy.ndarray

In [11]:
a2 = np.array([[1,2,4],
               [7,8,9]])

In [12]:
type(a2)

numpy.ndarray

#### Shape 

In [13]:
a2.shape

(2, 3)

#### ndim return so chieu 

In [14]:
a2.ndim

2

#### dtype return type of np array

In [15]:
a2.dtype

dtype('int32')

#### size return tong so element of np array

In [16]:
a2.size

6

## Creating Numpt Arrays from Scartch
#### zeros, ones, full, arrange, linspace

In [19]:
# zeros
np.zeros((2, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
# ones
np.ones((3, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# arange
np.arange(3, 10, 2)

array([3, 5, 7, 9])

In [24]:
# full
np.full((3, 5), 4.5)

array([[4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5]])

In [29]:
np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

#### Random

In [30]:
np.random.random((4, 4))

array([[0.26505758, 0.7051687 , 0.66928927, 0.15872639],
       [0.87976377, 0.8234436 , 0.85004356, 0.10545155],
       [0.52133397, 0.57565094, 0.52393271, 0.399493  ],
       [0.17149484, 0.24418027, 0.43940143, 0.22821263]])

In [31]:
np.random.random((4, 4))

array([[0.09333229, 0.35267968, 0.62452546, 0.60960502],
       [0.61599825, 0.0017747 , 0.8085726 , 0.60994151],
       [0.82327535, 0.9301207 , 0.59200874, 0.34449967],
       [0.16327748, 0.82958633, 0.40615687, 0.7642693 ]])

In [32]:
# Seed for reproducibility 
np.random.seed(0)

np.random.random((4, 4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [33]:
np.random.normal(0, 1, (3, 3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [38]:
np.random.rand(4, 4)

array([[0.89603839, 0.63892108, 0.89155444, 0.68005557],
       [0.44919774, 0.97857093, 0.11620191, 0.7670237 ],
       [0.41182014, 0.67543908, 0.24979628, 0.31321833],
       [0.96541622, 0.58846509, 0.65966841, 0.53320625]])

In [36]:
np.random.randint(0, 10, (4, 5))

array([[5, 0, 1, 5, 9],
       [3, 0, 5, 0, 1],
       [2, 4, 2, 0, 3],
       [2, 0, 7, 5, 9]])

## Array Indexing & Sliceing
#### Once-dimensional subarray

In [48]:
x1 = np.random.randint(20, size=(6))

In [49]:
x1

array([ 3, 18, 15,  3, 10, 12])

In [52]:
x1[4], x1[0], x1[-1]

(10, 3, 12)

#### Multi-dimensional aray

In [54]:
x2 = np.random.randint(10, size=(3, 4))
x2

array([[3, 9, 7, 5],
       [3, 4, 5, 3],
       [3, 7, 9, 9]])

In [55]:
x2[1, 2]

5

In [57]:
x2[1, 2] = 8
x2

array([[3, 9, 7, 5],
       [3, 4, 8, 3],
       [3, 7, 9, 9]])

#### Slicing:
##### x[start:stop:step]

In [58]:
x1

array([ 3, 18, 15,  3, 10, 12])

In [59]:
x1[0:3]

array([ 3, 18, 15])

In [67]:
x1[2:4]

array([15,  3])

In [69]:
# every other element, every 2 step
x1[::2]

array([ 3, 15, 10])

In [70]:
x2

array([[3, 9, 7, 5],
       [3, 4, 8, 3],
       [3, 7, 9, 9]])

In [71]:
# two rows, three columns
x2[:2, :3]

array([[3, 9, 7],
       [3, 4, 8]])

In [72]:
x2[:, :2]

array([[3, 9],
       [3, 4],
       [3, 7]])

In [73]:
x2[:2, 2:4]

array([[7, 5],
       [8, 3]])

### Reshaping of Arrays & Transpose

In [76]:
# reshape
grid = np.arange(1, 10)
grid.shape

(9,)

In [77]:
grid.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
x = np.array([1, 2, 3])
x.shape

(3,)

In [79]:
x.reshape((1, 3))

array([[1, 2, 3]])

#### Transpose

In [80]:
x = np.array([[1, 2], [3, 5]])
x

array([[1, 2],
       [3, 5]])

In [81]:
x.T

array([[1, 3],
       [2, 5]])

### Array Concatenation and Splitting

In [83]:
x = np.array([1, 2, 3])
y = np.array([3,2,1])

In [86]:
np.concatenate((x, y))

array([1, 2, 3, 3, 2, 1])

In [87]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
# axis = 0 by default concat row, axis = 1 concat colunm
np.concatenate((grid, grid), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [89]:
#vstack
x = np.array([1,2,3])
grid = np.array([[9,8,7], [6,5,4]])


In [90]:
# vertical (doc)
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [91]:
# horizontally stack the arrays: hstack (chieu ngang)
y = np.array([[99], [99]])
np.hstack((y, grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

### Splitting of arrays

In [94]:
x = np.array([1, 2,3,4,5,6,7,8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [96]:
x1, x2, x3 = np.split(x, [3,5])

In [98]:
x2

array([4, 5])

In [99]:
x3

array([6, 7, 8])

In [97]:
x1

array([1, 2, 3])

### Broadcasting and Vectorized operations

In [5]:
a = np.arange(3)
a

array([0, 1, 2])

In [6]:
a + 5 # Broadcasting

array([5, 6, 7])

In [7]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
a.shape, b.shape

((3,), (3, 3))

In [9]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [10]:
a.reshape((3, 1)) + a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [11]:
a * b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [13]:
c = a.reshape((3, 1))
c

array([[0],
       [1],
       [2]])

In [14]:
c + a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Manipulating & Compare Arrays

In [15]:
list_number = [1,2,3]

In [16]:
ll = np.array(list_number)
ll

array([1, 2, 3])

In [17]:
np.sum(ll)

6

In [18]:
new_ar = np.ones((3, 3))
new_ar


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.sum(new_ar)

9.0

#### Standard deviation

In [23]:
dog_height = [600, 470, 170, 430, 300]
dog_height = np.array(dog_height)
dog_height

array([600, 470, 170, 430, 300])

In [24]:
np.std(dog_height)

147.32277488562318

In [25]:
np.var(dog_height)

21704.0

In [26]:
np.sqrt(np.var(dog_height))

147.32277488562318

#### Sorting Arrays
###### np.sort users an quicksort algorith

In [4]:
x = np.array([2, 1, 4, 5, 3, 10])
np.sort(x)

array([ 1,  2,  3,  4,  5, 10])

In [5]:
# A related function is argsort, which instead returns the indices of the sorted elements:
# return index of element after sorting
np.argsort(x)

array([1, 0, 4, 2, 3, 5], dtype=int64)

### Sorting along rows or columns
##### NumPy's sorting algorithms is the ability to sort along specific row or columns of a multidemensional array using the axis argument

In [6]:
np.random.seed(42)
MatA = np.random.randint(0, 10, size=(4,6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [7]:
# sort columns
np.sort(MatA, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [8]:
np.sort(MatA, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

### Linear Algebra (Dai so tuyen tinh)

In [9]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [10]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
B = np.array([[6,5],
             [4,3],
             [2,1]])

In [13]:
# A(3*3) dot product B(3*2)
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [15]:
# Another approach A.dot(B)
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [14]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [16]:
 B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Dot Product Example

In [17]:
# Number of jars sold
np.random.seed(0)

sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [19]:
# Create weekly_sales DataFrame
import pandas as pd

weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                           columns = ["Almond Butter", "Peanut Butter", "Cashew Butter "])

In [20]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter 
Mon               12             15               0
Tues               3              3               7
Wed                9             19              18
Thurs              4              6              12
Fri                1              6               7

In [21]:
# create a price array 
prices = np.array([10,8,12])

In [23]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Price"], 
                            columns = ["Almond Butter", "Peanut Butter", "Cashew Butter "])

In [24]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter 
Price             10              8              12

In [26]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [28]:
total_prices = weekly_sales.dot(butter_prices.T)

In [29]:
total_prices

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [30]:
weekly_sales["Total Price"] = total_prices

In [34]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter   Total Price
Mon               12             15               0          240
Tues               3              3               7          138
Wed                9             19              18          458
Thurs              4              6              12          232
Fri                1              6               7          142