In [1]:
import numpy as np

## Create Array 

### 3-D Array
* An array that has 2-D arrays (matrices) as its elements is called 3-D array
* Mảng có mảng 2-D (ma trận) làm phần tử của nó được gọi là mảng 3-D

### 2-D Array
* An array that has 1-D arrays as its elements is called a 2-D array
* Mảng có mảng 1-D làm phần tử của nó được gọi là mảng 2-D

In [16]:
max3D = np.array([[[6,4,3], [2,1,0]], [[9,10,11],[11,12,13]]])
max3D

array([[[ 6,  4,  3],
        [ 2,  1,  0]],

       [[ 9, 10, 11],
        [11, 12, 13]]])

## Array Indexing
#### 2-D arrays

In [2]:
# create 
arr = np.array([[1,2,3,4], [4,5,6,7]])
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [3]:
# 2nd element on 1st dimention
arr[0, 1] #2

2

In [4]:
arr[0][1]

2

In [6]:
# Access the 3th element on 2nd dim:
arr[1][3]

7

#### 3-D arrays

In [8]:
X = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
X

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
X.ndim

3

In [10]:
X.shape

(2, 2, 3)

In [14]:
# Access the third element of the second array of the first array
# X[0][1][2]
X[0, 1, 2]

6

## Slicing Arrays

* Syntax: [start:end:step]
* The result includes the start index, but excludes the end index.
* (Kết quả bao gồm chỉ mục bắt đầu nhưng loại phần tử kết thúc)

#### Slicing 1-D Arrays

In [17]:
Y = np.array([1,2,3,4,5,6])
Y

array([1, 2, 3, 4, 5, 6])

In [19]:
# Slice elements from the beginning to index 4:
Y[:4] # 1 2 3 4

array([1, 2, 3, 4])

In [20]:
# Slice from the index 3 from the end to index 1 from the end:
Y[-3:-1] # 4 5

array([4, 5])

#### Slicing 2-D Arrays
* Matrix[rows, elememts which i want to get]

In [21]:
max2D = np.array([[1,2,3,4,5], [6,7,8,9,10]])
max2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
# From the second element, slice elements from index 1 to index 4
# max2D[1][1:4]
max2D[-1, 1:4]

array([7, 8, 9])

In [25]:
# From both elements, return index 2
max2D[0:2, 2]

array([3, 8])

In [26]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array
max2D[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

## NumPy Array Shape
* The shape of an array is the number of elements in each dimension (chiều)

In [27]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
arr.shape

(2, 4)

* The example above returns (2, 4), which means that the array has 2 dimensions, and each dimension has 4 elements.

In [30]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

In [31]:
arr.shape

(1, 1, 1, 1, 4)

## Reshape

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
# covert array 1D -> array 2D (4 dimension, 3 elements)
arr.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
# Reshape From 1-D to 3-D
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

* Theo thứ tự từ ngoài vào trong
* Dimension ngoài cùng có 2 elements
* Dimension thứ 2 có 3 elements
* Dimension thứ 3 có 2 elements

## NumPy Array Iterating
* Duyệt từng dòng của Matrix rồi mới duyệt đến elements

In [37]:
# 1D
arr = np.array([1, 2, 3])

for e in arr: 
    print(e)

1
2
3


In [39]:
# 2D
arr = np.array([[1, 2, 3], [4, 5, 6]])
for row in arr:
    print(row)

[1 2 3]
[4 5 6]


In [40]:
for row in arr:
    for ele in row:
        print(ele)

1
2
3
4
5
6


In [41]:
# Iterating 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [42]:
for x in arr:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [43]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


## NumPy Searching Arrays
* You can search an array for a certain value, and return the indexes that get a match

In [45]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
x

(array([3, 5, 6], dtype=int64),)

In [47]:
x = np.where(arr%2==0)
x

(array([1, 3, 5, 6], dtype=int64),)

## Random

#### Rand

In [2]:
np.random.rand(3,2)

array([[0.51516804, 0.73183063],
       [0.02165134, 0.60853674],
       [0.98915911, 0.50792128]])

#### Randn

In [5]:
np.random.randn(2, 4)

array([[ 0.65447746,  0.53340373,  0.02669781, -1.35788319],
       [ 0.73552266,  0.17242213,  0.74724774, -0.08744811]])

#### Randint
* Return random integers from low (inclusive) to high (exclusive)

In [7]:
np.random.randint(1, 11, size=(3,4))

array([[ 8,  3,  4,  4],
       [ 5,  5,  1,  4],
       [ 5,  7,  4, 10]])

#### Shuffle 
* (Xáo trộn nội dung của Mat)

In [20]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])